### ISSUE TITLE
more flexible dbt version requirement

### ISSUE THREAD

**Issue by bachng2017** [mindsdb/dbt-mindsdb#15]
may be this should be a little more flexible ?

https://github.com/mindsdb/dbt-mindsdb/blob/main/setup.py#L23

like below or something familiar

```
dbt-core>=1.0.1
```

**Comment by ZoranPandovski** [comment]
We need to migrate to the latest version, as described in https://github.com/mindsdb/dbt-mindsdb/issues/9

**Comment by bachng2017** [comment]
understood :)
